import React, { useState, useRef } from 'react';
import { reportsApi } from '../api';
import { Button } from './ui/Button';
import { Upload, CheckCircle2, XCircle, AlertTriangle, FileJson, X, ArrowRight } from 'lucide-react';

interface ImportModalProps {
  onClose: () => void;
  onSuccess: (studentId: string) => void;
}

type Step = 'upload' | 'processing' | 'result';

interface StepStatus {
  label: string;
  status: 'pending' | 'running' | 'done' | 'error';
}

export function ImportModal({ onClose, onSuccess }: ImportModalProps) {
  const [step, setStep] = useState<Step>('upload');
  const [file, setFile] = useState<File | null>(null);
  const [dragging, setDragging] = useState(false);
  const [error, setError] = useState('');
  const [result, setResult] = useState<any>(null);
  const fileInputRef = useRef<HTMLInputElement>(null);
  const [steps, setSteps] = useState<StepStatus[]>([
    { label: 'Uploading report file...', status: 'pending' },
    { label: 'Validating report structure...', status: 'pending' },
    { label: 'Extracting learning activity...', status: 'pending' },
    { label: 'Analyzing learning signals...', status: 'pending' },
    { label: 'Generating facilitator insights...', status: 'pending' },
  ]);

  const updateStep = (idx: number, status: StepStatus['status']) => {
    setSteps(prev => prev.map((s, i) => i === idx ? { ...s, status } : s));
  };

  const handleFile = (f: File) => {
    if (!f.name.endsWith('.json')) {
      setError('Only JSON report files are supported.');
      return;
    }
    setFile(f);
    setError('');
  };

  const handleDrop = (e: React.DragEvent) => {
    e.preventDefault();
    setDragging(false);
    const f = e.dataTransfer.files[0];
    if (f) handleFile(f);
  };

  const handleImport = async () => {
    if (!file) return;
    setStep('processing');

    try {
      // Animate steps
      for (let i = 0; i < steps.length; i++) {
        updateStep(i, 'running');
        await new Promise(r => setTimeout(r, i === 0 ? 200 : 400));
        updateStep(i, 'done');
      }

      const res = await reportsApi.import(file);
      setResult(res);
      setStep('result');
    } catch (err: any) {
      setStep('result');
      setError(err.message);
    }
  };

  return (
    <div className="fixed inset-0 bg-black/50 backdrop-blur-sm flex items-center justify-center z-50 p-4">
      <div className="bg-white rounded-2xl shadow-2xl w-full max-w-lg overflow-hidden">
        {/* Header */}
        <div className="flex items-center justify-between px-6 py-4 border-b border-gray-100">
          <div>
            <h2 className="font-semibold text-gray-900">Import Student Learning Report</h2>
            <p className="text-xs text-gray-500 mt-0.5">Upload a JSON report generated by the Acculum student app</p>
          </div>
          <button onClick={onClose} className="text-gray-400 hover:text-gray-600 p-1">
            <X size={20} />
          </button>
        </div>

        <div className="p-6">
          {/* STEP: Upload */}
          {step === 'upload' && (
            <div className="space-y-4">
              <div
                onDragOver={(e) => { e.preventDefault(); setDragging(true); }}
                onDragLeave={() => setDragging(false)}
                onDrop={handleDrop}
                onClick={() => fileInputRef.current?.click()}
                className={`border-2 border-dashed rounded-xl p-8 text-center cursor-pointer transition-all ${
                  dragging ? 'border-indigo-400 bg-indigo-50' : file ? 'border-emerald-400 bg-emerald-50' : 'border-gray-300 hover:border-indigo-400 hover:bg-indigo-50/50'
                }`}
              >
                <input
                  ref={fileInputRef} type="file" accept=".json" className="hidden"
                  onChange={(e) => { const f = e.target.files?.[0]; if (f) handleFile(f); }}
                />
                {file ? (
                  <div className="flex flex-col items-center gap-2">
                    <FileJson size={40} className="text-emerald-600" />
                    <p className="font-medium text-emerald-800">{file.name}</p>
                    <p className="text-sm text-emerald-600">{(file.size / 1024).toFixed(1)} KB · Ready to import</p>
                    <button
                      onClick={(e) => { e.stopPropagation(); setFile(null); }}
                      className="text-xs text-gray-400 hover:text-red-500 mt-1"
                    >
                      Remove file
                    </button>
                  </div>
                ) : (
                  <div className="flex flex-col items-center gap-3">
                    <div className="w-14 h-14 bg-indigo-100 rounded-full flex items-center justify-center">
                      <Upload size={24} className="text-indigo-600" />
                    </div>
                    <div>
                      <p className="font-medium text-gray-700">Drop report here or click to browse</p>
                      <p className="text-sm text-gray-400 mt-1">Accepts .json Acculum Student Learning Reports</p>
                    </div>
                  </div>
                )}
              </div>

              {error && (
                <div className="flex items-start gap-2 p-3 rounded-lg bg-red-50 border border-red-200 text-red-700 text-sm">
                  <XCircle size={16} className="shrink-0 mt-0.5" />
                  {error}
                </div>
              )}

              <div className="flex gap-3">
                <Button variant="secondary" onClick={onClose} className="flex-1 justify-center">Cancel</Button>
                <Button onClick={handleImport} disabled={!file} className="flex-1 justify-center" icon={<Upload size={15} />}>
                  Upload & Analyze
                </Button>
              </div>
            </div>
          )}

          {/* STEP: Processing */}
          {step === 'processing' && (
            <div className="space-y-3 py-2">
              <p className="text-sm text-gray-500 mb-4">Acculum is analyzing this report...</p>
              {steps.map((s, i) => (
                <div key={i} className="flex items-center gap-3">
                  <div className="w-5 h-5 flex-shrink-0">
                    {s.status === 'done' && <CheckCircle2 size={20} className="text-emerald-500" />}
                    {s.status === 'running' && (
                      <svg className="animate-spin h-5 w-5 text-indigo-500" xmlns="http://www.w3.org/2000/svg" fill="none" viewBox="0 0 24 24">
                        <circle className="opacity-25" cx="12" cy="12" r="10" stroke="currentColor" strokeWidth="4" />
                        <path className="opacity-75" fill="currentColor" d="M4 12a8 8 0 018-8V0C5.373 0 0 5.373 0 12h4z" />
                      </svg>
                    )}
                    {s.status === 'pending' && <div className="w-5 h-5 rounded-full border-2 border-gray-200" />}
                  </div>
                  <span className={`text-sm ${s.status === 'done' ? 'text-emerald-700' : s.status === 'running' ? 'text-indigo-600 font-medium' : 'text-gray-400'}`}>
                    {s.label}
                  </span>
                </div>
              ))}
            </div>
          )}

          {/* STEP: Result */}
          {step === 'result' && (
            <div className="space-y-4">
              {error ? (
                <div className="p-4 rounded-xl bg-red-50 border border-red-200">
                  <div className="flex items-center gap-2 text-red-700 font-medium mb-2">
                    <XCircle size={18} />
                    Import Failed
                  </div>
                  <p className="text-sm text-red-600">{error}</p>
                </div>
              ) : result && (
                <>
                  <div className="p-4 rounded-xl bg-emerald-50 border border-emerald-200 space-y-2">
                    {[
                      `Report verified (v${result.validation?.reportVersion || '1.0'})`,
                      `Student identified: ${result.student?.full_name} · Class ${result.student?.class}`,
                      result.validation?.activitiesCount ? `${result.validation.activitiesCount} lesson activities found` : null,
                      result.validation?.quizzesCount ? `${result.validation.quizzesCount} quizzes analyzed` : null,
                      `${result.signals_detected || 0} learning signal(s) detected`,
                    ].filter(Boolean).map((msg, i) => (
                      <div key={i} className="flex items-center gap-2 text-sm text-emerald-700">
                        <CheckCircle2 size={15} className="shrink-0 text-emerald-500" />
                        {msg}
                      </div>
                    ))}
                  </div>

                  {result.warnings?.length > 0 && (
                    <div className="p-3 rounded-lg bg-amber-50 border border-amber-200 space-y-1">
                      {result.warnings.map((w: string, i: number) => (
                        <div key={i} className="flex items-start gap-2 text-xs text-amber-700">
                          <AlertTriangle size={12} className="shrink-0 mt-0.5" />
                          {w}
                        </div>
                      ))}
                    </div>
                  )}

                  {result.ai_summary && (
                    <div className="p-4 rounded-xl bg-indigo-50 border border-indigo-100">
                      <p className="text-xs font-medium text-indigo-600 mb-1.5">Acculum Analysis Preview</p>
                      <p className="text-sm text-indigo-900 leading-relaxed">{result.ai_summary}</p>
                    </div>
                  )}
                </>
              )}

              <div className="flex gap-3 pt-2">
                <Button variant="secondary" onClick={onClose} className="flex-1 justify-center">Close</Button>
                {result?.student?.id && (
                  <Button
                    onClick={() => { onSuccess(result.student.id); onClose(); }}
                    className="flex-1 justify-center"
                    icon={<ArrowRight size={15} />}
                  >
                    View Student
                  </Button>
                )}
              </div>
            </div>
          )}
        </div>
      </div>
    </div>
  );
}
